### ISSUE TITLE
Custom Sorting window's issues

### ISSUE THREAD

**Issue by Kira-NT** [Kir-Antipov/LineSorter#3]
PLEASE make Custom Sorting windows sizable and/or properly assign dialog exit codes to windows buttons - they aren't visible with large DPIs and there is almost no way to show them or "press" using accelerator keys. Also please make valid valid components order for TAB key

--------

Author: [Yury Lebedev, review at Marketplace (26.01.2019)](https://marketplace.visualstudio.com/items?itemName=KirAntipov.LineSorterByKir#review-details)

**Comment by Kira-NT** [comment]
### Done!

I've set up normal **Tab-order** as well as **confirmation** and **cancel buttons** for *"Custom Sorting"* windows!

I've also made the *testing form* **sizable** (*creation form* can't be resizable, cause code input size depends on inner text measuring, no form height)

---------------

This fix will be available at the [Marketplace](https://marketplace.visualstudio.com/items?itemName=KirAntipov.LineSorterByKir) immediately after the first update (*LineSorter 4.0*)!

**Comment by yuryleb** [comment]
Just a few screenshots with initial problem (I'm using custom Ordinal sorting for phonetic dictionary):
<img width="960" alt="2019-01-28" src="https://user-images.githubusercontent.com/4529411/51848777-48017180-232f-11e9-8a6d-86177e7b08ab.png">
After several clicks on other controls I could get code text and buttons displayed:
<img width="960" alt="2019-01-28 1" src="https://user-images.githubusercontent.com/4529411/51848847-74b58900-232f-11e9-887f-f11d630d15ff.png">
But if I choose "test my method", I get window with no buttons and possibility to close it:
<img width="960" alt="2019-01-28 2" src="https://user-images.githubusercontent.com/4529411/51849000-d118a880-232f-11e9-937f-20c4a085e1e8.png">

BTW there are other issues:

- Custom sorting methods are not being loaded automatically - they're loaded only after Tools/Options dialog and LineSorter options touching
- There is no way to rename custom sorting (maybe I misprinted the name I would like to correct)- maybe it's possible to replace 'Custom sorts' table with an editable list box with check boxes to enable/disable sorters?

Anyway thank you for this simple and useful extension :wink:

**Comment by Kira-NT** [comment]
@yuryleb, thank you so much for the screenshots! 
Now it became clearer to me what was going on. Rather strange behavior of forms... I will try to fix it.
_(However, as I said, Tab-order is fixed, the Esc and Enter buttons now work as expected)_

-------------------------

> Custom sorting methods are not being loaded automatically

This is not entirely true: after the transition of Visual Studio to AsyncPackage, the download of third-party extensions does not go along with the launch of the IDE, but in parallel with the process of our work in it

The process of loading an extension is divided into 2 stages:
1. "Visible" initialization based on information from vsct (adding buttons to context menus, creating sections in settings, and so on)
2. Full initialization (direct code execution)

Primary initialization is performed immediately after launching Visual Studio, but for a full load, the extension will have to be queued

However, I set the following attributes for my extension package in order to queue it for initialization as soon as possible:
```
[ProvideAutoLoad(VSConstants.UICONTEXT.CodeWindow_string, PackageAutoLoadFlags.BackgroundLoad)]
[ProvideAutoLoad(VSConstants.UICONTEXT.SolutionOpening_string, PackageAutoLoadFlags.BackgroundLoad)]
[ProvideAutoLoad(VSConstants.UICONTEXT.FirstLaunchSetup_string, PackageAutoLoadFlags.BackgroundLoad)]
[ProvideAutoLoad(VSConstants.UICONTEXT.BackgroundProjectLoad_string, PackageAutoLoadFlags.BackgroundLoad)]
```

So there are several options:

- Either your computer runs the environment for a long time by itself.

- Or, you have installed quite a lot of extensions awaiting their initialization)

Your interaction with the extension just pulls it to the very top of the queue.

Unfortunately, this behavior cannot be changed (believe me, I spent a couple of nights with this), as it was laid by the creators of VisualStudio :crying_cat_face:

--------------------------

> There is no way to rename custom sorting

The fact is that the sort name is “stitched” into the compiled assembly, so renaming it would mean recompiling it 

This slightly tough decision protects the sorting from losing the name by which it could be identified (I doubt that anyone in the world has such a good memory to be content with the GUID value), and in principle, all the sortings from the loss of serviceable (I originally stored sorting in the SQLite file, until I accidentally deleted it during testing. Believe me, the consequences were rather unpleasant), so I decided to make the name an integral and unchangeable part of sorting)

------------------------------

> maybe it's possible to replace 'Custom sorts' table with an editable list box with check boxes to enable/disable sorters?

This functionality is already present in the extension: just right-click on the sort you want to enable / disable and select the desired action)

(I wrote about it on the main Marketplace page)

![its-here](https://user-images.githubusercontent.com/40232067/51919377-536aa080-23f4-11e9-813e-b70137fd0894.png)

--------------------------------------------------
> Anyway thank you for this simple and useful extension

Thank you very much for your wonderful words)<br>
Thank you for using my extension)

**Comment by Kira-NT** [comment]
### Update!

I found that this problem seems to be caused by the combination of the properties `FormBorderStyle = FixedSingle` and `ControlBox = false` with a large DPI. Apparently, this is a platform bug... 

I hope that the LineSorter 4.0 update will fix your problem!
(Will be ready for several days)

**Comment by Kira-NT** [comment]
@yuryleb, I've just published new LineSorter to Marketplace

Is it ok now?)

**Comment by yuryleb** [comment]
Yes, for now. Custom sorters are still not loaded initially but its creation dialog looks right:
<img width="385" alt="2019-02-13" src="https://user-images.githubusercontent.com/4529411/52715898-a6288880-2fae-11e9-8a31-d7dbd1841bcc.png">
But after typing first char in code text box the dialog gets distorted a bit:
<img width="385" alt="2019-02-13 1" src="https://user-images.githubusercontent.com/4529411/52716031-e5ef7000-2fae-11e9-9f42-8bcc7c209540.png">
And it still can be resized. But sorter test window can:
<img width="475" alt="2019-02-13 2" src="https://user-images.githubusercontent.com/4529411/52716165-3ebf0880-2faf-11e9-8f85-fec612e3e4ea.png">
